services:
  - type: web
    name: briefroom
    env: python
    plan: free
    buildCommand: pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production